### ISSUE TITLE
'Toda Erika, where the project name comes from'

### ISSUE THREAD

**Issue by MayuOshima** [ljsabc/MangaLineExtraction_PyTorch#1]
Maybe this is not something like an issue but is this Toda Erika the Japanese actress?
If so, I wonder why this project name comes from her(Just a little curious about this because it seems that the name is not so special. If this question is impolite I apologize first).

**Comment by ljsabc** [comment]
@MayuOshima I watched her drama and movies a lot when I first made this project 4 years ago. At that time I was on my PhD study and I used to watch Liar Games and SPEC during model training :D

**Comment by MayuOshima** [comment]
Thanks for your answering! 
なるほどね、sounds interesting！
